name: jmh_test
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - click=8.1.7
  - expat=2.6.4
  - idna=3.7
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmpdec=4.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - pysocks=1.7.1
  - python=3.13.2
  - python-dotenv=0.21.0
  - python_abi=3.13
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - urllib3=2.3.0
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - javalang==0.13.0
      - six==1.17.0
